services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=banking
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql